### ISSUE TITLE
Modification object has no attribute 'source_code_before'

### ISSUE THREAD

**Issue by shanushka** [ExpertiseModel/ZipfModel#1]
While running the application, I encountered two problems in the tokenizer file

1) Modification object has no attribute 'source_code_before'
  I tried using a different repository but still was facing the same issue.
  ![source_code_before](https://user-images.githubusercontent.com/20009772/120106238-0c377a80-c17c-11eb-896f-cf52a2327564.png)
  
2) If I remove this part 'Commit_before': modified_file.source_code_before, it gives me this error even if 
I initialized the tf_source = []

![f](https://user-images.githubusercontent.com/20009772/120106408-8c5de000-c17c-11eb-9529-5bd98600e654.png)

**Comment by ExpertiseModel** [comment]
Hi,
Thank you for your interest in ZipfModel.

please share how you define "tf_source" and also share the link of the repository that you are trying to scrape.

Between, here is the link to the pydriller documentation. You can find all objects related to modification files in this link:

https://pydriller.readthedocs.io/en/latest/modifiedfile.html

**Comment by shanushka** [comment]
The repository I am trying to clone is 'https://github.com/rwightman/gen-efficientnet-pytorch.git'

I installed pydriller 1.0 version since the latest version of pydriller doesn't have RepositoryMining.Even if I used the Respository from pydriller 2.0 , It shows the following error from this line
 ```for modified_file in commit.modifications:```
 
![commit](https://user-images.githubusercontent.com/20009772/120918616-ffafa680-c6d4-11eb-92ff-c11cca34f393.png)


If I use the pydriller-1.0 version,  I cannot use the external path
![zz](https://user-images.githubusercontent.com/20009772/120918693-6b920f00-c6d5-11eb-83c9-6a0720f99fd5.png)

When I clone the above repository and give the local path instead, it works.However even after everything has worked,
it states that MOdification object has no attribute source_code_before

![hh](https://user-images.githubusercontent.com/20009772/120918806-00950800-c6d6-11eb-82ac-06d9b55f2775.png)

**Comment by shanushka** [comment]
@ExpertiseModel Using pydriller-1.8 version solved the above error. I was trying to run the tokenizer file, but couldn't really get the code since it was not in sequential order and there are some trial codes that were not needed, and some of the files like 'tf_calls_tokens.csv' was missing.
Could you please give the repository_path under which the tokenizer file was working?

Also, how do we extract the novice_syn_data.csv and expert_syn_data.csv files that are used in ZipfModeling_syndt.ipynb
from tokenizer file.Since it is not defined in the tokenizer file?

**Comment by ExpertiseModel** [comment]
Hi,
In "tokenizer", first we describe with a step by step sample that how the parser works and extract the tokens from files before and after applying a commit. Then, we loop through all collected files and extract their tokens and save the result in 'tf_calls_tokens.csv' or 'cv_token' dataframe (they both have the same data). We just save the 'cv_token'  in a csv file, just to have a backup.

novice_syn_data.csv and expert_syn_data.csv files are in 'syn_data.zip'.

**Comment by shanushka** [comment]
Why do we use TfidfTransformer(). This has been used multiple times and some of the variables are not defined.
Also frequent_itemsets = frequent_itemsets.reset_index() is also defined but
frequent_itemsets has not been used elsewhere and same with
```LDA_model_ast = LatentDirichletAllocation(n_components=5,random_state=42)
AST_domain_results = LDA_model_ast.transform(All_LDA_tokens)
cv_token['domain'] = AST_domain_results.argmax(axis=1)
AST_Author_Domain=cv_token[['commit_Author','domain']]
AST_Author_groupby=AST_Author_Domain.groupby(['domain']).size().reset_index(name='count')
topic_per=((AST_Author_groupby)/len(AST_Author_Domain))*100```

Where are we using topic_per

**Comment by shanushka** [comment]
@ExpertiseModel I know that novice_syn_data.csv and expert_syn_data.csv files are in 'syn_data.zip'.I have used them as well but where do we extract these files from. In the tokenizer files, the column names that are given are not initialized or defined in the tokenizer file. Could you please explain how these data were refined and then converted to novice_syn_data.csv and expert_syn_data.csv files

**Comment by ExpertiseModel** [comment]
Hi Shanushka,

The 'apriori' and 'LDA' models are not related to the whole experiment. This is an extra experiment related to predicting the domain of expertise. I will comment that part out.
The most important part of 'tokenizer' is defined in code line '1427' to convert the python code into AST and then collect the differences after submitting a commit.

About 'novice_syn_data.csv' and 'expert_syn_data.csv', as you may already know, these are synthetic data. We generate this dataset by resampling real developers. Thus to generate such dataset, first, you need to select two (or more) sample developers, one expert and one novice. Then, you need to calculate the probability of tokens or SPs in these two sample developers, seperatley (with line 1427 and 1435 in the tokenizer, you can collect these tokens and their frequencies in developers commits). Function "token_probability" in "Model_train_realdt" in line '3020' can calculate this probability distribution for you. At the end, you use this vector of probability distribution as a weight vector to generate synthetic 'experts' and 'novice' developers.
Here is the code for generating synthetic datasets only for the expert category. You can replicate the loop with novice sample:

```
`dev_experts = pd.DataFrame(columns=['tokens','Author'])
for i in range(1,n):
    dev_name = 'exp_dev'+str(i)
    for i in range(1,m):
        keys=random.randint(1,s)
        r=random.choices(population=tokens,  weights=prob_exp, k=keys)
        dev_experts = dev_experts.append({'tokens':r , 'Author': dev_name},ignore_index=True)`
```

While 'n' is the number of developers (expert/novice) that you want to generate. 'm' is the number of commits per each developer and 's' is the number of tokens in each commit. To find the optimum values for these parameters, you can use the average of each value in your real dataset. 'tokens' is the list of distinct tokens. In 'tokenizer' in line 1427, the varaible 'vocab' captured all tokens in your real dataset. 'prob_exp' is the output of function "token_probability" in "Model_train_realdt" in line '3020' on your sample developer.

Hope it helps you :)

**Comment by ExpertiseModel** [comment]
I closed this issue since it's been a while since the last update. Please feel free to open a new one if you have any question.
